mod compact;
mod constants;
mod flow;
mod integer;
mod lexical;
mod preprocessor;
mod random;
mod rewrite;
mod simplify;
mod symbols;
mod syntax;

use std::collections::BTreeSet;
use std::error::Error as StdError;
use std::fmt;

/// Selects how much low-overhead source obfuscation is applied.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Profile {
    /// Rename symbols and render the configured source layout.
    Symbols,
    /// Also obfuscate literals and expression operator spellings.
    #[default]
    Balanced,
    /// Add strong function names, inline flow shards, arithmetic constants, and token noise.
    Maximum,
}

impl Profile {
    pub(crate) fn obfuscates_lexical_tokens(self) -> bool {
        self != Self::Symbols
    }

    pub(crate) fn reuses_local_names(self) -> bool {
        self != Self::Symbols
    }

    pub(crate) fn inserts_separator_comments(self) -> bool {
        self == Self::Maximum
    }

    pub(crate) fn uses_ambiguous_names(self) -> bool {
        self == Self::Maximum
    }

    pub(crate) fn obfuscates_arithmetic_constants(self) -> bool {
        self == Self::Maximum
    }

    pub(crate) fn splits_execution_flow(self) -> bool {
        self == Self::Maximum
    }

    pub(crate) fn uses_strong_function_names(self) -> bool {
        self == Self::Maximum
    }
}

/// Controls deterministic symbol renaming and source layout rendering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Options {
    /// Seed used to shuffle generated short identifiers.
    pub seed: u64,
    /// Collapse whitespace runs while preserving token and preprocessor boundaries.
    pub compact: bool,
    /// Remove comments without changing the parsed syntax structure.
    pub strip_comments: bool,
    /// Identifier spellings that must remain unchanged.
    pub preserve: BTreeSet<String>,
    /// Strength of symbol, flow, and lexical obfuscation.
    pub profile: Profile,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            seed: 0xC0FFEE,
            compact: true,
            strip_comments: true,
            preserve: BTreeSet::new(),
            profile: Profile::Balanced,
        }
    }
}

/// Failure produced while parsing, rewriting, or validating C++ source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ObfuscationError {
    /// Tree-sitter could not be initialized or did not return a syntax tree.
    ParserUnavailable,
    /// The normalized input contains a syntax error that cannot be handled conservatively.
    Syntax {
        /// One-based source line.
        line: usize,
        /// One-based byte column.
        column: usize,
        /// Tree-sitter node kind at the failure.
        kind: String,
    },
    /// The source uses a construct that cannot be rewritten conservatively.
    Unsupported(String),
    /// Internally generated byte edits conflict or split source boundaries.
    InvalidEdit(String),
    /// Re-parsing detected a structural change after a rewrite pass.
    Validation(String),
}

impl fmt::Display for ObfuscationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ParserUnavailable => write!(f, "Tree-sitter parser is unavailable"),
            Self::Syntax { line, column, kind } => {
                write!(f, "C++ syntax error at {line}:{column} near {kind}")
            }
            Self::Unsupported(message) => write!(f, "unsupported C++ construct: {message}"),
            Self::InvalidEdit(message) => write!(f, "invalid AST rewrite: {message}"),
            Self::Validation(message) => write!(f, "rewrite validation failed: {message}"),
        }
    }
}

impl StdError for ObfuscationError {}

/// Obfuscates one UTF-8 C++ translation unit.
///
/// Source-local macros are expanded and the resulting AST is simplified before
/// symbol analysis. Every later phase reparses its output. Identifier edits use
/// Tree-sitter byte ranges; maximum-profile flow shards and arithmetic
/// expressions establish new validated AST baselines before lexical rendering.
pub fn obfuscate(source: &str, options: &Options) -> Result<String, ObfuscationError> {
    let expanded = preprocessor::expand_local_macros(source)?;
    let simplified = simplify::simplify(&expanded)?;
    let original_tree = syntax::parse(&simplified)?;
    let original_signature = syntax::signature(original_tree.root_node());

    let edits = symbols::rename_edits(&simplified, original_tree.root_node(), options)?;
    let renamed = rewrite::apply(&simplified, &edits)?;
    let renamed_tree = syntax::parse(&renamed)?;
    syntax::ensure_same_structure(
        &original_signature,
        renamed_tree.root_node(),
        "identifier rewrite changed the syntax tree",
    )?;

    let flow = flow::split(
        &renamed,
        renamed_tree.root_node(),
        options.profile,
        options.seed,
    )?;
    let flow_tree = syntax::parse(&flow)?;

    let constant_edits =
        constants::encoding_edits(&flow, flow_tree.root_node(), options.profile, options.seed)?;
    let constant_rewrite = rewrite::apply_tracked(&flow, &constant_edits)?;
    let constants = constant_rewrite.output;
    let constants_tree = syntax::parse(&constants)?;
    constants::validate_replacements(
        &constants,
        constants_tree.root_node(),
        &constant_rewrite.replacement_ranges,
    )?;
    let expected_signature = syntax::signature(constants_tree.root_node());

    let lexical_edits = lexical::obfuscation_edits(
        &constants,
        constants_tree.root_node(),
        options.profile,
        options.seed,
    );
    let lexical = rewrite::apply(&constants, &lexical_edits)?;
    let lexical_tree = syntax::parse(&lexical)?;
    syntax::ensure_same_structure(
        &expected_signature,
        lexical_tree.root_node(),
        "lexical rewrite changed the syntax tree",
    )?;

    let output = compact::render(
        &lexical,
        lexical_tree.root_node(),
        options.compact,
        options.strip_comments,
        options.profile,
        options.seed,
    )?;
    let output_tree = syntax::parse(&output)?;
    syntax::ensure_same_structure(
        &expected_signature,
        output_tree.root_node(),
        "layout compaction changed the syntax tree",
    )?;

    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_invalid_cpp() {
        let error = obfuscate("int main( {", &Options::default()).unwrap_err();
        assert!(matches!(error, ObfuscationError::Syntax { .. }));
    }

    #[test]
    fn expands_statement_macros_before_parsing_the_body() {
        let source = r#"#define LOOP(i,n) for(int i=0;i<(n);++i)
int main(){int sum=0;LOOP(index,3){sum+=index;}return sum;}
"#;
        let output = obfuscate(
            source,
            &Options {
                profile: Profile::Symbols,
                ..Options::default()
            },
        )
        .unwrap();

        assert!(!output.contains("#define LOOP"));
        assert!(!output.contains("LOOP("));
        assert!(output.contains("for(int"));
        assert!(!output.contains("sum"));
        assert!(!output.contains("index"));
    }

    #[test]
    fn rejects_expression_macros_with_missing_semicolons() {
        let source = r#"#define EXPR(x) (x)
int main(){EXPR(1) {return 0;}}
"#;
        let error = obfuscate(source, &Options::default()).unwrap_err();

        assert!(matches!(error, ObfuscationError::Syntax { .. }));
    }

    #[test]
    fn expands_multiline_macros_and_preserves_physical_lines() {
        let source =
            "#define TWICE(x) \\\n ((x)+(x))\nint main(){int value=2;return TWICE(value);}\n";
        let output = obfuscate(source, &Options::default()).unwrap();

        assert!(!output.contains("#define TWICE"));
        assert!(!output.contains("TWICE"));
        assert!(output.contains("+"));
        assert!(!output.contains("value"));
        assert_eq!(
            source.bytes().filter(|byte| *byte == b'\n').count(),
            output.bytes().filter(|byte| *byte == b'\n').count()
        );
    }
}
