mod compact;
mod rewrite;
mod symbols;
mod syntax;

use std::collections::BTreeSet;
use std::error::Error as StdError;
use std::fmt;

/// Controls deterministic symbol renaming and source layout rendering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Options {
    /// Seed used to shuffle generated short identifiers.
    pub seed: u64,
    /// Collapse whitespace runs while preserving token and preprocessor boundaries.
    pub compact: bool,
    /// Remove comments without changing the parsed syntax structure.
    pub strip_comments: bool,
    /// Identifier spellings that must remain unchanged.
    pub preserve: BTreeSet<String>,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            seed: 0xC0FFEE,
            compact: true,
            strip_comments: true,
            preserve: BTreeSet::new(),
        }
    }
}

/// Failure produced while parsing, rewriting, or validating C++ source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ObfuscationError {
    /// Tree-sitter could not be initialized or did not return a syntax tree.
    ParserUnavailable,
    /// The input contains a syntax error that cannot be attributed to a supported statement macro.
    Syntax {
        /// One-based source line.
        line: usize,
        /// One-based byte column.
        column: usize,
        /// Tree-sitter node kind at the failure.
        kind: String,
    },
    /// The source uses a construct that cannot be rewritten conservatively.
    Unsupported(String),
    /// Internally generated byte edits conflict or split source boundaries.
    InvalidEdit(String),
    /// Re-parsing detected a structural change after a rewrite pass.
    Validation(String),
}

impl fmt::Display for ObfuscationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ParserUnavailable => write!(f, "Tree-sitter parser is unavailable"),
            Self::Syntax { line, column, kind } => {
                write!(f, "C++ syntax error at {line}:{column} near {kind}")
            }
            Self::Unsupported(message) => write!(f, "unsupported C++ construct: {message}"),
            Self::InvalidEdit(message) => write!(f, "invalid AST rewrite: {message}"),
            Self::Validation(message) => write!(f, "rewrite validation failed: {message}"),
        }
    }
}

impl StdError for ObfuscationError {}

/// Obfuscates one UTF-8 C++ translation unit.
///
/// The source is parsed before each phase. Identifier edits use Tree-sitter byte
/// ranges, and the final trees must retain the original non-comment structure.
pub fn obfuscate(source: &str, options: &Options) -> Result<String, ObfuscationError> {
    let original_tree = syntax::parse(source)?;
    let original_signature = syntax::signature(original_tree.root_node());

    let edits = symbols::rename_edits(source, original_tree.root_node(), options)?;
    let renamed = rewrite::apply(source, &edits)?;
    let renamed_tree = syntax::parse(&renamed)?;
    syntax::ensure_same_structure(
        &original_signature,
        renamed_tree.root_node(),
        "identifier rewrite changed the syntax tree",
    )?;

    let output = compact::render(
        &renamed,
        renamed_tree.root_node(),
        options.compact,
        options.strip_comments,
    )?;
    let output_tree = syntax::parse(&output)?;
    syntax::ensure_same_structure(
        &original_signature,
        output_tree.root_node(),
        "layout compaction changed the syntax tree",
    )?;

    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_invalid_cpp() {
        let error = obfuscate("int main( {", &Options::default()).unwrap_err();
        assert!(matches!(error, ObfuscationError::Syntax { .. }));
    }

    #[test]
    fn accepts_statement_macros_without_source_semicolons() {
        let source = r#"#define LOOP(i,n) for(int i=0;i<(n);++i)
int main(){int sum=0;LOOP(index,3){sum+=index;}return sum;}
"#;
        let output = obfuscate(source, &Options::default()).unwrap();

        assert!(output.contains("LOOP(index,3)"));
        assert!(!output.contains("sum"));
    }

    #[test]
    fn rejects_expression_macros_with_missing_semicolons() {
        let source = r#"#define EXPR(x) (x)
int main(){EXPR(1) {return 0;}}
"#;
        let error = obfuscate(source, &Options::default()).unwrap_err();

        assert!(matches!(error, ObfuscationError::Syntax { .. }));
    }

    #[test]
    fn preserves_multiline_macro_continuations() {
        let source =
            "#define TWICE(x) \\\n ((x)+(x))\nint main(){int value=2;return TWICE(value);}\n";
        let output = obfuscate(source, &Options::default()).unwrap();

        assert!(output.contains("\\\n"));
        assert!(output.contains("TWICE"));
        assert!(!output.contains("value"));
    }
}
